color: null
fieldLayouts:
  51f32229-5de2-4ec0-bcac-c4bc9c1df0f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-14T16:30:02+00:00'
            elementCondition: null
            fieldUid: 473ce54c-06f8-45af-a737-7aaeabffbfde
            handle: null
            includeInCards: true
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e34bf66-1913-40f6-af3a-d1527923058b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1acae64-7b7b-4d5d-bd90-a06e7a092563
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
