color: pink
fieldLayouts:
  18fdfbda-ae57-4895-b63c-2350f1292b48:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T17:26:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b2e21c01-ef2f-45a7-8db8-a05b6df4d718
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T16:30:02+00:00'
            elementCondition: null
            fieldUid: 782938c4-8296-4285-825e-8a68c0a0899b # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0030abb3-10fe-4e1d-b60c-12ab8ab3a459
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6492b6a0-f2b8-4a93-be48-20fad5e1d497
        userCondition: null
handle: quote
hasTitleField: false
icon: quotes
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
