color: null
fieldLayouts:
  3f024f9c-c06a-49c6-9224-4180d6b5aaf0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-14T16:30:02+00:00'
            elementCondition: null
            fieldUid: 782938c4-8296-4285-825e-8a68c0a0899b
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e7445e8-3c36-4e88-aea6-b0e41ed192dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3468b10-a164-459b-b2c4-e25312ada2fc
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
