color: null
fieldLayouts:
  3f024f9c-c06a-49c6-9224-4180d6b5aaf0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T17:27:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6edcce5b-1f5c-4b30-bd30-4df11e167d1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T16:30:02+00:00'
            elementCondition: null
            fieldUid: 782938c4-8296-4285-825e-8a68c0a0899b # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e7445e8-3c36-4e88-aea6-b0e41ed192dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3468b10-a164-459b-b2c4-e25312ada2fc
        userCondition: null
handle: text
hasTitleField: false
icon: font
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
