columnSuffix: null
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  createButtonLabel: 'Add block'
  entryTypes:
    - 5e86add9-56fa-4012-a62c-15a24415e5e0 # Image
    - 2633adaf-c526-44c9-885e-a6272d8f0a26 # Text
    - 423216e9-be60-4b68-a48f-32690ba804dc # Quote
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
