columnSuffix: xghluocz
handle: quote
instructions: null
name: 'Post Content - Quote - Quote'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
