columnSuffix: acuemsza
handle: text
instructions: null
name: 'Post Content - Text - Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 10
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
