defaultPlacement: end
enableVersioning: true
entryTypes:
  - 228d4acb-c42e-4d3d-ad21-8dc3d1ea0027 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6fe7500a-704e-4c0f-94ef-a868e4251578: # Tutorial
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
